Add pre-commit hooks for jupyter notebooks
merantix-momentum/squirrel-datasets-core pull request #54
Opened 2022-09-09 14:07 UTC by pzdkn

# Description

We have our example notebooks in the sq-ds-core repo. To standardize notebook outputs, prevent private information leakage, and reduce PR diffs, we can introduce an nbstripout precommit hook.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-datasets-core.readthedocs.io/en/latest/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-09-09 14:07 UTC, pzdkn commented
I have read the CLA Document and I hereby sign the CLA

2022-09-09 15:09 UTC, AlpAribal commented
/gcbrun

2022-09-09 15:29 UTC, AlpAribal requested changes
I was able to push a notebook with outputs (in a separate branch) using this configuration. Could you make a dummy commit with outputs in the PR so that we check that the hook is working?

2022-09-09 15:29 UTC, AlpAribal commented on .pre-commit-config.yaml
> +        stages: [push]
Only `push` means that we do not run this hook during cbuild, right? I think we would definitely want to run it

2022-09-14 09:59 UTC, pzdkn commented on .pre-commit-config.yaml
> +        stages: [push]
I am still fixing this. This is some installation problems. The `push` I added to avoid the outputs cleaned after every commit.

2022-09-14 15:19 UTC, pzdkn commented
Currently, there is an [issue](https://github.com/kynan/nbstripout/issues/168) with nbstripout, that prevents it from been run locally. I have created a [mirror-repository](https://github.com/pzdkn/mirror-nbstripout) implementing the changes that would fix the issue until it's solved at nbstripout's side.

2022-09-20 14:12 UTC, winfried-ripken commented
> Currently, there is an [issue](https://github.com/kynan/nbstripout/issues/168) with nbstripout, that prevents it from been run locally. I have created a [mirror-repository](https://github.com/pzdkn/mirror-nbstripout) implementing the changes that would fix the issue until it's solved at nbstripout's side.

Nice catch!

2022-09-21 08:47 UTC, merged